### ISSUE TITLE
Error running app.

### ISSUE THREAD

**Issue by edwardb6** [moshi4/pyGenomeViz#17]
Error running app.

**Comment by moshi4** [comment]
Is this issue letting me know that there is an error with the application on Streamlit Cloud (https://pygenomeviz.streamlit.app)?
I believe this error has now been fixed.

The application on https://pygenomeviz.streamlit.app is for demonstration purposes only, so if you want to visualize your own data, I recommend that you run the pyGenomeViz application in your local environment.
