### ISSUE TITLE
Load custom dataset gbk

### ISSUE THREAD

**Issue by GM110Z** [moshi4/pyGenomeViz#18]
Hello,

I am trying to use pyGenomeViz, with the mmseq feature, with a bunch of custom gbk files I have. However, following the tutorials I am having trouble to find a way to load my own dataset rather than the example ones. I have tried to use Genbank( gbk_source: Path ), but it won't work. 
I managed to customise the output the way i wanted it using a jupyter notebook, so i would like to be able to use that with my files. 
Could you advise what is the best way to load  my own dataset in a jupyter notebook ? 
Thanks

**Comment by GM110Z** [comment]
Hi Sorry
That is what I meant, I was trying to replace gbk_file with my path to dataset and below is the error i got
ValueError                                Traceback (most recent call last)
Cell In[1], line 12
      3 from tempfile import TemporaryDirectory
      5 gv = GenomeViz(
      6     fig_track_height=0.7,
      7     link_track_ratio=2.0,
      8     align_type="center",
      9     tick_style="bar",
     10 )
---> 12 gbk_files, _ = load_dataset("/Users/giusym/Desktop/Serratia_prophage/hotspot63/")
     14 for idx, gbk_file in enumerate(gbk_files):
     15     gbk = Genbank(gbk_file)

File ~/miniconda3/envs/m1/lib/python3.11/site-packages/pygenomeviz/utils.py:105, in load_dataset(name, cache_dir, overwrite_cache)
    103 if name not in DATASETS.keys():
    104     err_msg = f"'{name}' dataset not found."
--> 105     raise ValueError(err_msg)
    107 # Dataset cache local directory
    108 if cache_dir is None:

ValueError: '/path/to/dataset/' dataset not found.

**Comment by moshi4** [comment]
`load_dataset()` is a function to get genbank files of some species as examples. 
It is not a function for users to build their own datasets.

If you already have your own genbank file, there is no need to call `load_dataset()` function.

**Comment by GM110Z** [comment]
Ah ok thank you!
