### ISSUE TITLE
function to specify hatch patterns

### ISSUE THREAD

**Issue by sejmodha** [moshi4/pyGenomeViz#24]
Hi There,

First of all, thanks for developing this neat tool. It is impressive and works very well for genomic features viz and comparison.

I found the `facecolor_handle_func` very useful and was wondering if there is a way to specify hatch/patterns for each category too? Ideally, a function handler param would be perfect!

Thanks
Sej

**Comment by moshi4** [comment]
Hi @sejmodha,

I think you can do what you want as follows.

```python
from pygenomeviz import Genbank, GenomeViz, load_example_dataset

# Load genbank file (Set target min-max range)
gbk_files, _ = load_example_dataset("escherichia_phage")
gbk = Genbank(gbk_files[0], min_range=10000, max_range=25000)

# Plot min-max range genbank features
gv = GenomeViz()
track = gv.add_feature_track(name=gbk.name, size=gbk.range_size, start_pos=gbk.min_range)
track.add_genbank_features(gbk, label_type="protein_id", plotstyle="arrow", facecolor="skyblue", labelsize=10, linewidth=1)
track.set_sublabel(position="top-left")

# Change hatch pattern by feature strand category
for feature in track.features:
    hatch_ptn = "//" if feature.strand == 1 else "o"
    if feature.patch_kws is None:
        feature.patch_kws = dict(hatch=hatch_ptn)
    else:
        feature.patch_kws.update(dict(hatch=hatch_ptn))
    # Other plot parameters can also be changed
    facecolor = "skyblue" if feature.strand == 1 else "orange"
    feature.facecolor = facecolor

gv.savefig("result.png")
```

**result.png**
![result](https://github.com/moshi4/pyGenomeViz/assets/41852815/d4e614ac-abf1-424a-97e2-be3b16ce4df8)

**Comment by sejmodha** [comment]
Okay, thanks for confirming this! 
I managed to get something working based on the facecolor parameter as I needed to distinguish between very similar colours!

Thank you so much once again! :)
