### ISSUE TITLE
BioPython genbank records 

### ISSUE THREAD

**Issue by sejmodha** [moshi4/pyGenomeViz#27]
Hi There,

I was wondering if it is possible to use standard BioPython genbank records using something like `Genbank(gbk_source = record)` in pygenomeviz? If not, what is the best solution instead of splitting multi-record GenBank files into individual files?

Thanks
Sej

**Comment by moshi4** [comment]
Hi @sejmodha,

When handling multi-record(contig) Genbank files, it may be a good idea to use `gbk.get_seqid2size()` and `gbk.get_seqid2features()`.

**Code Example**

Plot the Genbank multi-record(contig) on each track. Works with latest pyGenomeViz **v0.4.4**.

[Mycoplasma_7contigs.zip](https://github.com/moshi4/pyGenomeViz/files/13227784/Mycoplasma_7contigs.zip)

```python
from pygenomeviz import GenomeViz
from pygenomeviz.parser import Genbank

# Parse genbank file
gbk_file = "Mycoplasma_7contigs.gbk"
gbk = Genbank(gbk_file)
# Extract genome size & CDS features per contig
seqid2size = gbk.get_seqid2size()
seqid2features = gbk.get_seqid2features(feature_type=None)

gv = GenomeViz(fig_track_height=0.7)

for seqid in seqid2size.keys():
    contig_size = seqid2size[seqid]
    contig_features = seqid2features[seqid]

    track = gv.add_feature_track(seqid, size=contig_size)
    track.set_sublabel()

    for feature in contig_features:
        if feature.type == "CDS":
            track.add_features([feature], plotstyle="arrow")
        elif feature.type == "rRNA":
            track.add_features([feature], plotstyle="arrow", facecolor="skyblue")
        elif feature.type == "tRNA":
            track.add_features([feature], plotstyle="arrow", facecolor="magenta")

gv.savefig("multi_contigs.png")
```

**multi_contigs.png**
![multi_contigs](https://github.com/moshi4/pyGenomeViz/assets/41852815/fdae32c8-5c44-4195-b04c-654613a31726)

**Comment by sejmodha** [comment]
Thanks @moshi4 - I will try this out.

**Comment by sejmodha** [comment]
Hi @moshi4,

I was wondering if it would be possible to use `add_genbank_features` in this example? Or how could I use several params available within `add_features`? e.g. `facecolor_handle_func` and `feature_type` 

Thanks
Sej

**Comment by moshi4** [comment]
> I was wondering if it would be possible to use add_genbank_features in this example?

It is impossible to use `add_genbank_features`.

> how could I use several params available within add_features? e.g. facecolor_handle_func and feature_type

I don't quite understand the intent of the question. I think you should take a look at the API documentation for [`add_features`](https://moshi4.github.io/pyGenomeViz/api-docs/track/#pygenomeviz.track.FeatureTrack.add_features).

**Comment by sejmodha** [comment]
Sorry for any confusion.

I wanted to say that some settings, like `facecolor_handle_func`, can't be used with `add_features`, only with `add_genbank_features` and `add_gff_features`.

Here's some background: I'm using the `add_genbank_features` method to handle individual genbank files, saving each record separately as `*.gbk` files. Now, I want to create genome diagrams from a genbank file with multiple records (where there's more than one). I see that I can use the `add_features` method, as you demonstrated above, but there are slight differences in the available params between `add_features` and `add_genbank_features`. According to the documentation, the `facecolor_handle_func` isn't implemented in `add_features` but is available in `add_genbank_features` and `add_gff_features`. I'm curious if there's a reason for this difference and if it's possible to add support for `facecolor_handle_func` in the `add_features` method.

I hope this clears things up.

**Comment by moshi4** [comment]
>I'm curious if there's a reason for this difference and if it's possible to add support for facecolor_handle_func in the add_features method

I thought the *facecolor_handle_func* argument was unnecessary, so I intentionally removed it from `add_features` method. This is because `add_features` allows user to arbitrarily change facecolor, hatch, etc. for each feature even without *facecolor_handle_func*. Therefore, there is no plan to implement an additional *facecolor_handle_func* argument to `add_features` method in the future.
