### ISSUE TITLE
AttributeError: 'SeqFeature' object has no attribute 'strand'

### ISSUE THREAD

**Issue by biogeeker** [moshi4/pyGenomeViz#29]
Hi, first of all, i want to thank you for these wonderful tools. 

I have a question about running the demo in the Colab notebook `getting_started.ipynb`. Here’s the error I encountered:

### ### 2-1. Add Features from Genbank file
... ...

```
from pygenomeviz import Genbank, GenomeViz, load_example_dataset

gbk_files, _ = load_example_dataset("enterobacteria_phage")
gbk = Genbank(gbk_files[0])

gv = GenomeViz()
track = gv.add_feature_track(name=gbk.name, size=gbk.range_size)
track.add_genbank_features(gbk)  # By default, add `CDS` type features

fig = gv.plotfig()


---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

[<ipython-input-24-e0ba53fb72c5>](https://localhost:8080/#) in <cell line: 8>()
      6 gv = GenomeViz()
      7 track = gv.add_feature_track(name=gbk.name, size=gbk.range_size)
----> 8 track.add_genbank_features(gbk)  # By default, add `CDS` type features
      9 
     10 fig = gv.plotfig()

1 frames

[/usr/local/lib/python3.10/dist-packages/pygenomeviz/parser/genbank.py](https://localhost:8080/#) in extract_features(self, feature_type, target_strand, fix_position, allow_partial, pseudogene)
    359                         if translation is None:
    360                             continue
--> 361                 if f.strand == -1:
    362                     # Handle rare case (complement & join)
    363                     # Found in NC_00913 protein_id=NP_417367.1
```

Everything in the Colab notebook is set to default. Could you please suggest how to fix this?

**Comment by moshi4** [comment]
Hi @biogeeker,

In the latest BioPython v1.82 update (December 22), the *strand* property of SeqFeature has been removed and a change to `feature.location.strand` instead of `feature.strand` is required.
Therefore, you need to install v1.81 instead of BioPython v1.82 with the following command to make the current version of pyGenomeViz work properly.

    pip install pygenomeviz biopython==1.81

This issue will be resolved in the next release of pyGenomeViz.

**Comment by biogeeker** [comment]
Yeah, the error has been fixed. Thank you very much!!!
