### ISSUE TITLE
Issue with visualize.py Script Execution Leading to ValueError

### ISSUE THREAD

**Issue by ZiliaMR** [moshi4/pyGenomeViz#31]
Hi,

I've been using your visualize.py script from the [pyGenomeViz repository](https://github.com/moshi4/pyGenomeViz/blob/main/notebooks/fastANI/visualize.py) with the following command:

```
python visualize.py LM32_112contigs_filtered.fasta GCF_024448155.1_filtered.fasta LM32_test.visual plot_LM32vs024448155 
```

However, I encounter the following error during execution:

```
Traceback (most recent call last):
  File "/Users/zili/Dropbox/Zilia/Proyectos/Streptomyces_Nitrogeno/2024/data_NCBI/genomic_fna/rename/visualize.py", line 130, in <module>
    main()
  File "/Users/zili/Dropbox/Zilia/Proyectos/Streptomyces_Nitrogeno/2024/data_NCBI/genomic_fna/rename/visualize.py", line 65, in main
    track2.add_feature(link2[1], link2[2], plotstyle="bigbox", facecolor=color)
  File "/opt/anaconda3/envs/fastani/lib/python3.12/site-packages/pygenomeviz/track.py", line 381, in add_feature
    self._within_valid_range(start, end, raise_error_on_false=True)
  File "/opt/anaconda3/envs/fastani/lib/python3.12/site-packages/pygenomeviz/track.py", line 222, in _within_valid_range
    raise ValueError(err_msg)
ValueError: 'GCF_024448155.1_filtered' track start-end range must be '0 <= start <= end <= 8137678' (start=8135052, end=8138051 is invalid)
```

The GCF_024448155.1_filtered.fasta file contains a total of 364 contigs, and the LM32_112contigs_filtered.fasta file contains 112 contigs. Could the issue be related to the contig count or sizes in these files?

I would appreciate any guidance on resolving this error or suggestions for troubleshooting steps I might take.

Thank you for your time and assistance.

Best regards,

**Comment by moshi4** [comment]
Do you get the above error after executing the following commands, including running fastANI?

```shell
fastANI -q LM32_112contigs_filtered.fasta -r GCF_024448155.1_filtered.fasta --visualize -o LM32_test
python visualize.py LM32_112contigs_filtered.fasta GCF_024448155.1_filtered.fasta LM32_test.visual plot_LM32vs024448155 
```

The information given is not enough to determine the cause of the problem. If you upload your input file, it may be possible to find out the cause of the error.

**Comment by ZiliaMR** [comment]
Hello,

I encountered an issue when running the `visualize.py` script following the fastANI analysis. The initial command I executed was:

```
fastANI -q LM32_112contigs_filtered.fasta --rl list_refgenomes.txt --visualize -o LM32_test
```

The `list_refgenomes.txt` file contains one genome file per line. The output from this command appears to be correct. However, when I tried to run the `visualize.py` script with the following command:

```
python visualize.py LM32_112contigs_filtered.fasta GCF_024448155.1_filtered.fasta LM32_test.visual plot_LM32vs024448155 
```

I received an error. Interestingly, when I reran the fastANI command using only `GCF_024448155.1_filtered.fasta` as the reference genome and then executed the `visualize.py` script, it worked without issues (like your previous comment). The error seems to occur only when using the list of reference genomes.

**Comment by moshi4** [comment]
> The error seems to occur only when using the list of reference genomes.

The result of outputting `--rl`(reference list) instead of `-r`(reference) as an option in fastANI cannot be used in `visualize.py`. It is natural that an error would occur since the result of fastANI, which is not expected, is taken as input.

**Comment by ZiliaMR** [comment]
Hello again,

I apologize for the repeated inquiries, but it seems that the error with the visualize.py script persists, this time with a different file. [Here](https://drive.google.com/drive/folders/1gI4iWcq6AOYobn-2gDahaLGv_nGRxK0n?usp=sharing) are the inputs and below are the commands I used for this instance. I would greatly appreciate it if you could take another look.

```
fastANI -q LM65_93contigs_filtered.fasta -r GCF_000720835.1_filtered.fasta --visualize -o LM65
python visualize.py LM65_93contigs_filtered.fasta GCF_000720835.1_filtered.fasta LM65.visual plot_LM65v000720835

```

Thank you for your time and help.

**Comment by moshi4** [comment]
I am confused because the name of the uploaded file is different from the name of the file specified in the command.

**Comment by ZiliaMR** [comment]
ooh my bad, I have uploaded the correct file.

**Comment by moshi4** [comment]
I ran the same command and the error did not occur in my environment. Since I cannot reproduce the error, it is difficult for me to give advice.

**plot_LM65v000720835.png**

![plot_LM65v000720835](https://github.com/moshi4/pyGenomeViz/assets/41852815/96ad82f3-b0b9-43a8-b2da-d79ecbc58e39)

**Comment by ZiliaMR** [comment]
yes, I rerun the command and it's worked! maybe I was tired :( ,  Sorry. 

Thank you for your assistance. 
Great script.
