### ISSUE TITLE
How to make the link between two tracks instead of two genes

### ISSUE THREAD

**Issue by Dx-wmc** [moshi4/pyGenomeViz#39]
Hi, this may not be a required feature, but one that I want to implement. Usually, the comparison of two genes focuses on the lower part of the gene to the upper part of the other fragment, but I would like to implement the link to focus between the two traces as shown in the picture. I tried to modify your link.py, but due to too much complexity I didn't realize this feature. Can you provide me with some suggestions?
<img width="166" alt="image" src="https://github.com/moshi4/pyGenomeViz/assets/63085833/b80846c0-9d2c-4d5a-ace6-48865d64af14">

**Comment by moshi4** [comment]
pyGenomeViz is designed with clearly divided plot areas (matplotlib Axes) by FeatureTrack and LinkTrack, respectively. Therefore, it is probably difficult to implement your requested feature in pyGenomeViz.

**Comment by Dx-wmc** [comment]
I tried it and when I added this section to the genomeviz.py script I found that I could extend the area of the link, but alignment is really a headache, it would be nice to get a little help from you! 

` elif isinstance(track, LinkTrack):

                link_track_height_ratio = height_ratios[idx]
                total_height_ratio = sum(height_ratios)
                link_track_relative_position = sum(height_ratios[:idx]) / total_height_ratio

                start_idx = max(0, idx - 1)
                end_idx = min(idx + 1, len(height_ratios) - 1)
                link_track_relative_height = (height_ratios[idx] + sum(height_ratios[start_idx:end_idx+1])) / total_height_ratio / 2
                
                l = link_track_height_ratio / total_height_ratio
                bottom = 1 - (link_track_relative_position + 1.2 * l)
                #bottom = 1 - (link_track_relative_position+link_track_relative_height)
                height = link_track_relative_height
                ax.set_position([0, bottom, 1, height])

                for link in track.links:
                    # Don't plot too small link (To reduce drawing time)
                    length1, length2 = link.track_length1, link.track_length2
                    if 0 < length1 < plot_length_thr or 0 < length2 < plot_length_thr:
                        continue
                    link = link.add_offset(self._track_name2link_offset)
                    link.plot_link(ax, ylim)
`

**Comment by moshi4** [comment]
Sorry, I am not going to spend the time and effort to support how to do this.
