### ISSUE TITLE
Request to Retain Previous Version Tutorials

### ISSUE THREAD

**Issue by Dx-wmc** [moshi4/pyGenomeViz#41]
Hi, I am excited to see the significant update to the software. I have briefly tested the new version, but as you mentioned, my previous code is no longer compatible. Given the extensive differences between the versions, I would like to suggest retaining the old tutorials alongside the new ones. This would be incredibly helpful for long-time users who have invested time and effort into learning and utilizing the previous version.

**Comment by moshi4** [comment]
I think you are suggesting that it would be desirable to be able to switch versions of the documentation site (`v1.0.0` <-> `v0.4.4`). I'll consider it if it can be done easily with GitHub Actions. Please do not expect too much and wait.

**Comment by Dx-wmc** [comment]
Thank you for considering my suggestion. I understand that implementing the ability to switch between documentation versions might take some time and effort.

In the meantime, if possible, could you provide a PDF or HTML version of the previous documentation? Having access to the old documentation would be immensely helpful for me to understand the differences between the versions, and to adapt my existing code to the new version. Previously, I heavily relied on the tutorials, so the version change has made it challenging for me to transition without knowing the old commands and parameters.

**Comment by moshi4** [comment]
Uploaded pygenomeviz v0.4.4 documentation at the following link.
https://moshi4.github.io/docs/pygenomeviz/v0.4.4/

`Open in Colab` link and some image links are broken, but I think it is somewhat usable.

**Comment by Dx-wmc** [comment]
It works. Thank you very much！
