### ISSUE TITLE
display portion of contig from multi-record Genbank files

### ISSUE THREAD

**Issue by phyto** [moshi4/pyGenomeViz#43]
Thank you very much again for this new version of pyGenomeViz! I definitely think that API changes in v1.1.0 will make it even simpler and easier to display our favorite genomes, despite compatibility breaks with previous versions. I like also very much the example of plotting user-defined annotations, which I needed.
I still have two small questions though.
1) The first question is about multi-record Genbank files.  Let's say we would need to display range 0-20000 of contig NZ_LAEX01000008.1 from GCF_000959065.1 from Mycoplasma mycoides subsp. mycoides (example dataset). Based on provided examples, I ended up with the following code but I was wondering if I there was a more straigthforward possibility that I would have missed?

```
from pygenomeviz import GenomeViz
from pygenomeviz.parser import Genbank
from pygenomeviz.utils import load_example_genbank_dataset, is_pseudo_feature
from pygenomeviz.utils import extract_features_within_range

gbk_files = load_example_genbank_dataset("mycoplasma_mycoides")
gbk = Genbank(gbk_files[-1])

gv = GenomeViz(fig_track_height=0.5)
gv.set_scale_bar(ymargin=0.5)

# Set contigs as segments
track = gv.add_feature_track(gbk.name,{'NZ_LAEX01000008.1': (0,20000)},
                             space=0.03)

seqid2features = gbk.get_seqid2features(feature_type=None)
for segment in track.segments:
    # Plot contig features per segment
    features = seqid2features[segment.name]
    features_within_range = extract_features_within_range(
        features, target_range=(segment.start, segment.end))    
    for feature in features_within_range:
        # Set user-defined feature color based on feature type & pseudo tag
        if feature.type == "CDS":
            color = "grey" if is_pseudo_feature(feature) else "blue"
            segment.add_features(feature, color=color)
        elif feature.type == "rRNA":
            segment.add_features(feature, color="lime")

fig = gv.plotfig()
```
2) The second question is about an inversion option. I am aware that Biopython offers a reverse_complement method that can be used to display reversed contigs. However I was wondering if pyGenomeViz 1.1.0  was also providing something about this, like for version 0.4.4?

**Comment by moshi4** [comment]
> 1. The first question is about multi-record Genbank files. ~~~

I don't think there is a more straighforward way.

> 2. The second question is about an inversion option. ~~~

Use BioPython(SeqRecord) `reverse_complement()` method. I'm not really thinking of implementing the same functionality in pyGenomeViz.
