### ISSUE TITLE
Why pgv-pmauve doesn't report identity value

### ISSUE THREAD

**Issue by Rohit-Satyam** [moshi4/pyGenomeViz#44]
Hi @moshi4 

I have 3 fasta files for the virus genome i.e. 1 closest reference, 1 Canu assembly, and 1 Flye assembly and I am trying to see which one is good based on alignment with the reference, but since there is no identity value given by pgv-pmauve.

**Comment by moshi4** [comment]
This is because pregressiveMauve does not report identity value. So it is impossible for pgv-pmauve to report identity value.
