### ISSUE TITLE
Plot genome comparison links from an existing `align_coords.tsv`

### ISSUE THREAD

**Issue by amara86** [moshi4/pyGenomeViz#46]
Hi 
I want to align my reference genome with assemblies and have files about 1.5G each in size. I have generated align_coords.tsv file but its image is not being produced on HPC. Is there a way to directly use tsv file to create an image of genome comparisons?
Thanks

**Comment by moshi4** [comment]
If you are using the CLI and want to reuse the existing `align_coords.tsv`, you can use the --reuse option.
