### ISSUE TITLE
issue with tooltips

### ISSUE THREAD

**Issue by phyto** [moshi4/pyGenomeViz#47]
Dear Moshi
I like very much the possibility to display info about individual genes using tooltips when looking at html figures generated with pygenomeviz. However it seems the tooltips are not always displayed. In particular in my case it seems that tooltips are displayed for hatched genes but not unhatched ones. Here is an example code (for Windows) that reproduces this behavior (green-hatched arrows display a tooltip, the yellow ones don't).
Thank you!

```
from pygenomeviz import GenomeViz
from pygenomeviz.parser import Genbank
from pygenomeviz.utils import load_example_genbank_dataset

from pathlib import Path
import webbrowser

gbk_files = load_example_genbank_dataset("yersinia_phage")
gbk = Genbank(gbk_files[0])

gv = GenomeViz(fig_track_height=0.7)
gv.set_scale_bar(ymargin=0.5)

track = gv.add_feature_track(gbk.name, gbk.genome_length)
track.add_sublabel()

# Plot genbank features
features = gbk.extract_features()

counter = 0
for feature in features:
    if feature.type=='CDS':
        if counter%2==0 : 
            patch_prop = {'facecolor':'green',  'hatch':'/'}
        else:
            patch_prop = {'facecolor':'yellow'}
        track.add_features(feature, plotstyle="bigarrow",lw=0.5, **patch_prop)
        counter = counter + 1

fig = gv.plotfig()
output_file = Path("test.html")
gv.savefig_html(output_file, fig)
firefox = webbrowser.get('windows-default')
print('file:///' + str(output_file.absolute()))
firefox.open('file:///' + str(output_file.absolute()), new=2)
```

**Comment by moshi4** [comment]
I could not reproduce the issue you describe, at least in my linux environment. Since I can't reproduce it, it is difficult to solve the problem.

**Comment by phyto** [comment]
It works like a charm when using `fast_render=False`, thank you very much!!
