### ISSUE TITLE
Representation of enhancer links

### ISSUE THREAD

**Issue by r-trimbour** [moshi4/pyGenomeViz#50]
Hello dear developpers,

First, thanks a lot for your great package ! :)

I am currently looking for a python package to **represent enhancer-promoter connections** and I was wondering if there is any way of using pygenomeviz to obtain a result like [Cicero](https://cole-trapnell-lab.github.io/cicero-release/docs_m3/#visualizing-cicero-connections) does in R (1st image).

I tried to do it repurposing the add_exon_feature function, but I didn't know how/what to modify to make the "intron" 1) above the regions, 2) centered and/or 3) curved.  I was wondering thus if you had any more straightforward method or function that could be used to reach this result, and if not, what functions should I look at to modify the intron representation to reach such plotting ?

Thanks a lot for your help ! :heart: 
Rémi

![comparison_track_m3](https://github.com/moshi4/pyGenomeViz/assets/77151348/8a61e8fa-2e96-4938-b747-9b71d1f23ab2)
![Example_repurposing_intron_into_enhancer_promoterlinks](https://github.com/moshi4/pyGenomeViz/assets/77151348/f85623f2-7983-4e9f-8413-fd50da29aa65)

**Comment by moshi4** [comment]
Hi @r-trimbour,

> I didn't know how/what to modify to make the "intron" 1) above the regions, 2) centered and/or 3) curved.

Unfortunately, the functionality to achieve these is not present in pyGenomeViz.
The priority of implementing exon-intron-related visualization functions in pyGenomeViz is low, so there are no plans to implement them in the future.
