### ISSUE TITLE
support annotations stacked more thant two deep

### ISSUE THREAD

**Issue by diekhans** [moshi4/pyGenomeViz#55]
This is a really nice package. Unfortunately, I hit a wall because the overlapping annotations were more than two deep and were drawn overlapping rather than stacked.

Would be nice if deeper stacking was supported

![notch2nl](https://github.com/user-attachments/assets/e54edc3c-335d-4887-87c7-ad95cd49bddb)

**Comment by moshi4** [comment]
Using `to_stack_features()` function added in the latest v1.3.0 release, I think you can now do what you want to do. Since pyGenomeViz was not originally designed to stack and plot features, it seems difficult to implement it any easier than this.

**Code Example**

```python
from pygenomeviz import GenomeViz
from pygenomeviz.utils import to_stack_features
from Bio.SeqFeature import SeqFeature, SimpleLocation

# Create example features
locs = [(10, 20), (30, 50), (60, 90)]
features = [SeqFeature(SimpleLocation(loc[0], loc[1])) for loc in locs]

locs = [(10, 20), (15, 25), (18, 30), (30, 50), (70, 100), (80, 85), (90, 100)]
overlap_features = [SeqFeature(SimpleLocation(loc[0], loc[1])) for loc in locs]

gv = GenomeViz(fig_track_height=0.5)

# Plot features
track = gv.add_feature_track("features", 100)
track.add_features(features, plotstyle="bigarrow")

# Plot overlap features on stack tracks
stack_features = to_stack_features(overlap_features)
for idx, sublist_features in enumerate(stack_features):
    track = gv.add_feature_track(f"track{idx}", 100)
    track.add_features(sublist_features, plotstyle="bigarrow", color="blue")

    # Set small link track ratio
    if idx > 0:
        gv.link_tracks[-1].set_ratio(0.1)
        track.set_label("")
    else:
        track.set_label("overlap features")

fig = gv.plotfig()
fig.savefig("result.png")
```

**result.png**

![result](https://github.com/user-attachments/assets/bb4b1809-c69a-4540-a47b-ec94d59817df)
