### ISSUE TITLE
Demo Page is down

### ISSUE THREAD

**Issue by MilagrosLG** [moshi4/pyGenomeViz#59]
Help, what s wrong with the demo web page?

**Comment by moshi4** [comment]
I rebooted the Demo Page app and resolved the issue.

[Demo Page](https://pygenomeviz.streamlit.app/) is deployed on the free Streamlit Cloud, which has low CPU and memory resources. Therefore, the app sometimes crashes due to lack of resources.

**Comment by MilagrosLG** [comment]
thank you so much
