### ISSUE TITLE
adding different annotations in the hover screen in html

### ISSUE THREAD

**Issue by dadush1** [moshi4/pyGenomeViz#61]
Hi moshi4!
First of all thank you for a wonderful tool! its great!
One thing that I couldn't quite understand is how to control which text will be shown when hovering on a gene in html mode.
For example this:
![image](https://github.com/user-attachments/assets/7b226749-d8ab-438b-b9d1-3690a1201d23)

this is how I add features to the track, but only "length" and "location" are shown in the box, the label is pasted above the gene, I would like it also to show in the hover box:

`        # add genes to genome track
        for cds in cds_list:
            start, end, strand, name, color, patch_kws, linewidth = cds
            track.add_feature(start, end, strand, label=name, facecolor = color, patch_kws = patch_kws, labelsize = 7, labelvpos = vposition, labelrotation = labelrotation, linewidth = linewidth)
`

This is how it looks in my case:
![image](https://github.com/user-attachments/assets/f7a6309d-c041-40e3-b550-b1b1fcf3ab3c)

Thanks!

**Comment by moshi4** [comment]
In pyGenomeViz `v1.0.0 or later`, tooltip labels can be added freely with the extra_tooltip argument.

**Code Example**

```python
from pygenomeviz import GenomeViz

gv = GenomeViz()
gv.set_scale_xticks(ymargin=0.5)

track = gv.add_feature_track("tutorial", 1000)
track.add_sublabel()

track.add_feature(50, 200, 1, extra_tooltip=dict(name="gene1", type="CDS"))
track.add_feature(250, 460, -1, fc="blue", extra_tooltip=dict(name="gene2", type="CDS", product="hypothetical"))
track.add_feature(500, 710, 1, fc="lime", extra_tooltip=dict(name="16S rRNA", type="rRNA"))
track.add_feature(750, 960, 1, fc="magenta", lw=1.0)

gv.savefig_html("result.html")
```

![pygenomeviz_extra_tooltip](https://github.com/user-attachments/assets/05e030db-6602-4f55-864f-90473b574b0b)
