### ISSUE TITLE
Arrow size

### ISSUE THREAD

**Issue by woodoo46** [moshi4/pyGenomeViz#67]
Hi there,

Is there a way to control the size of the arrow? For example, when draw an arrow in "add_feature", can we change the size of the arrow?

Thanks.

George

**Comment by moshi4** [comment]
Hi @woodoo46,

I'm not sure what exactly you mean by `Arrow size`, but I'll try to answer your question.

Arrow head length cannot be changed. Arrow shaft size can be changed with the *arrow_shaft_ratio* argument of [add_feature](https://moshi4.github.io/pyGenomeViz/api-docs/track/#pygenomeviz.track.feature.FeatureTrack.add_feature) method.

**Comment by woodoo46** [comment]
Yeah, I think you answered my question. I mean the arrow head. Sometimes, if the segment being drawn is short relative to the whole region, there is only a big arrow head shown. Thanks for the wonderful package, it saves my day.
