### ISSUE TITLE
No module named 'pygenomeviz' 

### ISSUE THREAD

**Issue by dplazas** [moshi4/pyGenomeViz#69]
Hi 
I wanted to try this tool and after installing it (via pip3) and trying examples from here I got:

"ModuleNotFoundError: No module named 'pygenomeviz' "

the package is installed (verified by pip3 show pygenomeviz; Version: 0.4.4)

what's going on? (I could not find a "step by step" guide so perhaps I am missing something; I am used to R and not much to Python)
thanks

**Comment by moshi4** [comment]
This is not a problem with pyGenomeViz itself, but with your python runtime environment. I am not willing to help individual users solve their own runtime environment problems, so please do your own research on the common causes of ModuleNotFoundError in python and solve it yourself.

**Comment by dplazas** [comment]
OK.
