### ISSUE TITLE
Break the segment without gene features

### ISSUE THREAD

**Issue by chtsai0105** [moshi4/pyGenomeViz#70]
Hi -

I used pyGenomeViz to show the MAT loci of several species in Rhodotorula genus. It was great, provide a lot of flexibility to adjust the figure as much as I want. However, part of the MAT genes are found pretty far away from the others in some of the species/strains, which might due to recombinations. Currently pyGenomeViz does not support broken axis feature on segments but I think it might be really useful.

I'm thinking to skip the region sorounded by red tildes.
![image](https://github.com/user-attachments/assets/504e4aab-5bbc-4160-91cc-f247bcc8679c)

**Comment by moshi4** [comment]
It is a bit tedious to implement, but I think what you want to do could be accomplished by dividing and assigning the scaffold region of interest to a segment.

**Code Example**

```python
from pygenomeviz import GenomeViz

gv = GenomeViz()
gv.set_scale_bar()

track1 = gv.add_feature_track(
    name="Rhodotorula_toruloides_CBS14",
    segments=dict(CAKLCE030000024=(1505951, 1749024))
)

track2 = gv.add_feature_track(
    name="Rhodotorula_toruloides_DBVPG_6739",
    segments=dict(scaffold_25_1=(88656, 120000), scaffold_25_2=(250000, 288582), scaffold_14=(307, 149905)),
    space=[0.02, 0.05],
)
track2.set_segment_sep(sep=[True, False])

for track in gv.feature_tracks:
    for seg in track.segments:
        seg.add_sublabel(f"{seg.name}\n{seg.start:,} - {seg.end:,} bp")

gv.savefig("result.png")
```

**result.png**

![result](https://github.com/user-attachments/assets/101bb5b1-5bc2-4314-9bab-9cce3356be50)

**Comment by chtsai0105** [comment]
Yes, that was exactly what I've done so far. But the thing is I also want to label genes to the segments, and the easiest way I can do this is to modify the gff files directly. However, I also want to link the syntenic blocks by blastn results and I'll need to also change the sequence names in the fasta files to match the changes in the gff files...

**Comment by moshi4** [comment]
Whichever approach you take to achieve your desired plot, it is inevitable that input file editing or coding will be somewhat cumbersome.
